apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-metrics-collector
  namespace: gpu-metrics-test
spec:
  selector:
    matchLabels:
      app: gpu-metrics-collector
  template:
    metadata:
      labels:
        app: gpu-metrics-collector
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: node6
      containers:
      - name: gpu-collector
        image: python:3.9-slim
        command:
        - /bin/bash
        - -c
        - |
          set -ex
          
          echo "=== Starting setup ==="
          
          # Setup error handling
          error_handler() {
            echo "Error on line $1"
            exit 1
          }
          trap 'error_handler $LINENO' ERR
          
          echo "Installing packages..."
          apt-get update
          apt-get install -y python3-pip curl procps netcat net-tools iproute2
          
          echo "Verifying ROCm installation..."
          if [ ! -d "/opt/rocm" ]; then
            echo "ROCm directory not found!"
            ls -la /opt/
            exit 1
          fi
          
          echo "Installing Python packages..."
          pip install kubernetes prometheus-client
          
          echo "Checking network configuration..."
          ip addr
          netstat -tulpn
          
          echo "Testing port availability..."
          if netstat -tulpn | grep :19400; then
            echo "Port 19400 is already in use!"
            exit 1
          fi
          
          echo "Environment variables:"
          env | grep -i python
          env | grep -i exporter
          
          echo "Checking collector script..."
          if [ ! -f "/app/collector.py" ]; then
            echo "Collector script not found!"
            ls -la /app/
            exit 1
          fi
          
          echo "Starting collector with debug output..."
          cd /app
          PYTHONUNBUFFERED=1 PYTHONPATH=/app python3 -u /app/collector.py 2>&1
        ports:
        - containerPort: 19400
          hostPort: 19400
          name: metrics
          protocol: TCP
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: EXPORTER_PORT
          value: "19400"
        - name: DEBUG
          value: "1"
        volumeMounts:
        - name: collector-script
          mountPath: /app
        - name: rocm
          mountPath: /opt/rocm
        - name: sys
          mountPath: /sys
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: collector-script
        configMap:
          name: gpu-collector-script
          defaultMode: 0777
      - name: rocm
        hostPath:
          path: /opt/rocm
      - name: sys
        hostPath:
          path: /sys
