apiVersion: v1
kind: Pod
metadata:
  name: node-debugger
  namespace: gpu-metrics-test
spec:
  hostNetwork: true  # Use host network
  hostPID: true      # Access host processes
  nodeSelector:
    kubernetes.io/hostname: node6
  containers:
  - name: debugger
    image: ubuntu:22.04
    command: 
    - /bin/bash
    - -c
    - |
      apt-get update
      apt-get install -y netstat-nat net-tools curl lsof
      
      while true; do
        echo "=== $(date) ==="
        echo "Checking network interfaces..."
        ip addr
        
        echo "Checking listening ports..."
        netstat -tulpn | grep 9400 || echo "No process on 9400"
        
        echo "Checking process list..."
        ps aux | grep python || echo "No python process found"
        
        echo "Checking if port is reachable..."
        curl -v localhost:9400/metrics || echo "Port 9400 not reachable"
        
        echo "Checking active connections..."
        netstat -an | grep 9400
        
        echo "=== End of check ==="
        sleep 5
      done
    securityContext:
      privileged: true  # Required for host access
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
