apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-metrics-collector
  namespace: gpu-metrics-test
spec:
  selector:
    matchLabels:
      app: gpu-metrics-collector
  template:
    metadata:
      labels:
        app: gpu-metrics-collector
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: node6
      containers:
      - name: gpu-collector
        image: python:3.9-slim
        command:
        - /bin/bash
        - -c
        - |
          set -x
          
          echo "Starting installation..."
          apt-get update
          apt-get install -y python3-pip curl procps netcat net-tools iproute2
          
          echo "Installing Python packages..."
          pip install kubernetes prometheus-client
          
          echo "Checking system status..."
          ip addr
          netstat -tulpn
          
          echo "Checking ROCm..."
          ls -l /opt/rocm
          rocm-smi || echo "ROCm SMI not found"
          
          echo "Environment variables:"
          env
          
          echo "Starting collector with debug output..."
          PYTHONUNBUFFERED=1 PYTHONPATH=/app python3 -u /app/collector.py
        ports:
        - containerPort: 19400
          hostPort: 19400
          name: metrics
          protocol: TCP
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: EXPORTER_PORT
          value: "19400"
        volumeMounts:
        - name: collector-script
          mountPath: /app
        - name: rocm
          mountPath: /opt/rocm
        - name: sys
          mountPath: /sys
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
      volumes:
      - name: collector-script
        configMap:
          name: gpu-collector-script
          defaultMode: 0777
      - name: rocm
        hostPath:
          path: /opt/rocm
      - name: sys
        hostPath:
          path: /sys
